version: '2'
services:
  nodejs:
    build:
      context: .
      dockerfile: DockerFile
    ports:
      - "4000:4000"
    links:
      - redis
    expose:
      - "4001"
  redis:
    build:
      context: .
      dockerfile: Dockerfile-redis